[package]
name = "hyprcfg"
version = "0.1.0"
edition = "2021"

[dependencies]
freedesktop-icons = "0.2.6"
freedesktop_entry_parser = "1.3.0"
image = "0.25.5"
ini = "1.3.0"
slint = "1.8.0"
tux-icons = "0.3.0"
walkdir = "2.5.0"

[build-dependencies]
slint-build = "1.8.0"
