export component ActionBtn inherits HorizontalLayout {
  in property <image> icon-left  <=> imgLeft.source;
  in property <image> icon-right <=> imgRight.source;
  in property <string> text      <=> txtEl.text;

  callback clicked <=> tArea.clicked;

  alignment: start;

  Rectangle {
    height: 45px;
    background:
      tArea.pressed
        ? rgba(217, 217, 217, 0.08)
        : tArea.has-hover
          ? rgba(217, 217, 217, 0.22)
          : rgba(217, 217, 217, 0.08);


    border-radius: 5px;

    animate background {
      duration: 300ms;
      easing: ease-out-expo;
    }

    HorizontalLayout {
      alignment: start;

      VerticalLayout {
        alignment: center;
        padding-right: 11px;
        padding-left: 11px;

        imgLeft := Image {
          width: 22px;
          height: 22px;
          colorize: rgba(163, 171, 182, 1);
        }
      }

      Rectangle {
        height: parent.height - 6px;
        width: 1px;
        y: 3px;
        background: rgba(217, 217, 217, 0.06);
      }

      VerticalLayout {
        alignment: center;
        padding-right: 8px;
        padding-left: 8px;

        txtEl := Text {
          font-size: 12px;
          font-family: "Ubuntu";
          font-weight: 400;
          color: rgba(163, 171, 182, 1);
        }
      }

      VerticalLayout {
        alignment: center;
        padding-right: 10px;
        padding-left: 10px;

        imgRight := Image {
          width: 14px;
          height: 14px;
          colorize: rgba(163, 171, 182, 1);
        }
      }
    }

    tArea := TouchArea {
      mouse-cursor: MouseCursor.pointer;
    }
  }
}
