export component FadeModal inherits Rectangle {
  background: rgba(13, 14, 15, 0.80);

  width: 100%;
  height: 100%;

  x: 0px;
  y: 0px;

  VerticalLayout {
    alignment: center;

    HorizontalLayout {
      alignment: center;

      Rectangle {
        background: rgba(24, 32, 38, 0.97);
        border-radius: 8px;
        border-width: 1px;
        border-color: rgba(53, 63, 72, 0.46);

        width: 385px;
        height: 455px;

        @children
      }
    }
  }
}
