import {
  Section,
  SectionBox,
  SectionTitle
} from "../widgets/boxes.slint";

import { ActionBtn } from "../widgets/buttons.slint";
import { FadeModal } from "../widgets/modal.slint";
import { LineEdit } from "../widgets/input.slint";

import { UIState, AppEntry } from "../globals.slint";

export global TabletUIState {
  in-out property <[AppEntry]> app-entries;
  in-out property <bool> show-app-selection-modal: false;

  in-out property <string> search-query;
  callback fetch-app-entries;
  callback filter-app-entries(string);
}

export component TabletSection inherits Section {
  title: "Drawing Tablet";

  init => { TabletUIState.fetch-app-entries(); }

  SectionBox {
    icon: @image-url("../icons/link.svg");
    title: "Application-specific presets";

    VerticalLayout {
      padding-top: 15px;
      padding-bottom: 15px;

      padding-left: 10px;
      padding-right: 10px;

      alignment: center;

      HorizontalLayout {
        alignment: center;

        ActionBtn {
          icon-left: @image-url("../icons/box.svg");
          text: "Add application";
          icon-right: @image-url("../icons/arrow-down.svg");
          clicked => {
            TabletUIState.show-app-selection-modal = true;
          }
        }
      }
    }
  }
}

export component List inherits Rectangle {
  Flickable {
    width: 100%;

    VerticalLayout {
      padding: 10px;
      spacing: 5px;
      alignment: start;

      @children
    }
  }
}

export component ListItem inherits Rectangle {
  border-radius: 8px;
  width: 100%;
  clip: true;

  background: area.has_hover
    ? rgba(46, 49, 50, 0.4)
    : rgba(46, 49, 50, 0.0);

  animate background {
    duration: 500ms;
    easing: ease-out-expo;
  }

  area := TouchArea {
    mouse-cursor: MouseCursor.pointer;
    width: 100%;
    height: 100%;
  }

  HorizontalLayout {
    alignment: start;
    padding: 10px;

    @children
  }
}

export component AppSelectionModal inherits FadeModal {
  private property <string> search-query;


  VerticalLayout {
    alignment: stretch;
    height: 100%;

    header := HorizontalLayout {
      alignment: center;
      padding-top: 10px;
      height: 60px;

      search-field := LineEdit {
        placeholder-text: "Search applications...";
        placeholder-color: rgba(163, 171, 182, 0.5);
        text-color: rgba(163, 171, 182, 0.9);
        text <=> search-query;
        font-size: 14px;
        width: 250px;
        margin: 10px;
        horizontal-alignment: TextHorizontalAlignment.center;

        changed => {
          TabletUIState.filter-app-entries(search-query);
        }
      }
    }

    if TabletUIState.app-entries.length == 0: Rectangle {}
    if TabletUIState.app-entries.length > 0: VerticalLayout {
      vertical-stretch: 1;

      List {
        for entry in TabletUIState.app-entries: ListItem {
          height: 55px;

          //if search-query !==

          VerticalLayout {
            alignment: center;
            Image {
              source: entry.icon;
              width: 38px;
              height: 38px;
            }
          }

          VerticalLayout {
            alignment: center;
            spacing: 2px;
            padding-left: 8px;

            Text {
              text: entry.name;
              font-size: 14px;
              font-weight: 600;
              color: rgba(163, 171, 182, 0.9);
            }

            Text {
              text: entry.description;
              font-size: 12px;
              font-weight: 400;
              overflow: TextOverflow.elide;
              color: rgba(163, 171, 182, 0.9);
            }
          }
        }
      }
    }

    actions := HorizontalLayout {
      height: 50px;

      Rectangle {
        background: rgba(46, 49, 50, 0.4);

        HorizontalLayout {
          TouchArea {
            mouse-cursor: MouseCursor.pointer;

            Text {
              text: "Select";
              font-size: 16px;
              color: rgba(163, 171, 182, 0.9);
            }
          }

          Rectangle {
            height: parent.height - 6px;
            width: 1px;
            y: 3px;
            background: rgba(217, 217, 217, 0.06);
          }

          TouchArea {
            mouse-cursor: MouseCursor.pointer;

            clicked => {
              TabletUIState.show-app-selection-modal = false;
            }

            Text {
              text: "Cancel";
              font-size: 16px;
              color: rgba(163, 171, 182, 0.9);
            }
          }
        }
      }
    }
  }
}
