import { UIState } from "globals.slint";

import { Sidebar } from "components.slint";

import { HyprSection } from "sections/hypr.slint";
import { PkgsSection } from "sections/pkgs.slint";
import { ScreenSection } from "sections/screen.slint";
import { ThemeSection } from "sections/theme.slint";
import { WallpaperSection } from "sections/wallpaper.slint";

import {
  TabletSection,
  AppSelectionModal,
  TabletUIState
} from "sections/tablet.slint";

component SettingsView inherits Rectangle {
  private property <string> activeView;
  in-out property active <=> activeView;

  if active == "hypr": HyprSection {}
  if active == "pkgs": PkgsSection {}
  if active == "screen": ScreenSection {}
  if active == "tablet": TabletSection {}
  if active == "theme": ThemeSection {}
  if active == "wallpaper": WallpaperSection {}
}

component ModalsView inherits Rectangle {
  if TabletUIState.show-app-selection-modal:
    AppSelectionModal {}
}

export component MainWindow inherits Window {
  default-font-family: "Ubuntu";
  callback populate;

  no-frame: true;
  min-width: 535px;
  background: @linear-gradient(180deg,
    rgba(13, 14, 15, 0.89) 0%,
    rgba(13, 14, 15, 0.80) 100%);

  in-out property <string> activeSection: "hypr";

  HorizontalLayout {
    Sidebar { active <=> activeSection; }
    SettingsView { active <=> activeSection; }
  }

  ModalsView {}
}

export { UIState, TabletUIState }
