component CircleBtn inherits Rectangle {
  width: 30px;
  height: 30px;
  border-radius: 30px;
  background: rgba(23, 29, 34, 1);

  in property <image> icon;

  Image {
    source: icon;
    colorize: rgba(163, 171, 182, 1);

    width: 16px;
    height: 16px;
  }
}

component MenuBtn inherits Rectangle {
  callback clicked (string);

  in property <string> name;
  in property <image> icon;
  in property <string> label;

  width: 70px;
  height: 70px;

  background: tArea.has-hover
    ? rgba(163, 171, 182, 0.2)
    : rgba(23, 29, 34, 1);
  border-radius: 10px;

  animate background {
    duration: 300ms;
    easing: ease-out-expo;
  }

  VerticalLayout {
    alignment: center;

    HorizontalLayout {
      alignment: center;

      Image {
        source: icon;
        colorize: rgba(163, 171, 182, 1);

        width: 35px;
        height: 35px;
      }
    }

    HorizontalLayout {
      alignment: center;

      Text {
        text: label;
        color: rgba(163, 171, 182, 1);
      }
    }
  }

  tArea := TouchArea {
    mouse-cursor: MouseCursor.pointer;
    clicked => { root.clicked(name); }
  }
}

export component Sidebar inherits Flickable {
  width: 100px;

  private property <string> activeItem;
  in-out property <string> active <=> activeItem;

  VerticalLayout {
    Rectangle {
      width: 100px;
      height: 100%;

      background: rgba(13, 21, 26, 1);

      VerticalLayout {
        VerticalLayout {
          spacing: 10px;

          HorizontalLayout {
            alignment: center;
            spacing: 13px;
            padding-right: 5px;
            padding-left: 5px;
            padding-top:12px;

            CircleBtn {
              icon: @image-url("./icons/x.svg");
            }

            CircleBtn {
              icon: @image-url("./icons/refresh.svg");
            }
          }

          Rectangle {
            x: 5px;
            height: 1px;
            border-radius: 2px;
            width: parent.width - 10px;

            background: rgba(217, 217, 217, 0.06);
          }
        }

        VerticalLayout {
          alignment: start;
          spacing: 10px;
          padding: 15px;

          MenuBtn {
            icon: @image-url("./icons/magicpen.svg");
            name: "theme";
            label: "Theme";
            clicked (name) => { root.activeItem = name; }
          }

          MenuBtn {
            icon: @image-url("./icons/gallery.svg");
            name: "wallpaper";
            label: "Wallpaper";
            clicked (name) => { active = name; }
          }

          MenuBtn {
            icon: @image-url("./icons/screen.svg");
            name: "screen";
            label: "Screen";
            clicked (name) => { root.active = name; }
          }

          MenuBtn {
            icon: @image-url("./icons/3d-square.svg");
            name: "pkgs";
            label: "Pkgs";
            clicked (name) => { root.active = name; }
          }

          MenuBtn {
            icon: @image-url("./icons/tablet.svg");
            name: "tablet";
            label: "Tablet";
            clicked (name) => { root.active = name; }
          }

          MenuBtn {
            icon: @image-url("./icons/grid.svg");
            name: "hypr";
            label: "Hypr";
            clicked (name) => { root.active = name; }
          }
        }
      }
    }
  }
}

component Menu inherits Rectangle { }


export component HTabLayout inherits HorizontalLayout {
  Sidebar { }

  Rectangle {
    @children
  }
}

