export global UIColors {
// #182026
// #D9D9D9
// #0D151A -> sidebar
// #171D22 -> MenuBtn
// #A3ABB6 20% -> MenuBtn hover

// #353F48 -> border

  out property <brush> foreground: #A3ABB6;
  out property <brush> text: #A3ABB6;
}


export struct AppEntry {
  name: string,
  description: string,
  wm_class: string,
  icon: image,
}

export global UIState {
  in-out property <string> testStr: "pristine";

  in-out property <[AppEntry]> appEntries;
  in-out property <bool> show-app-selection-modal: false;

  callback fetch-app-entries;
}

